scc/mailing/urls.py
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView
from django.contrib.auth.decorators import login_required
from .views import *

app_name='mailing'

url_users = [
	path('', login_required(UserListView.as_view()), name='users'),
    path('create', login_required(UserCreateView.as_view()), name='create'),
	path('edit/<ids>', login_required(UserUpdateView.as_view()), name='users-edit'),
    path('edit-send/post', login_required(UserUpdateView.ajax_post), name='post-ajax'),
    path('edit-send/school', login_required(UserUpdateView.ajax_school), name='school-ajax'),
    path('edit-send/department', login_required(UserUpdateView.ajax_department), name='department-ajax'),
]

url_groups = [
    path('', login_required(GroupListView.as_view()), name='groups'),
    path('group-create', login_required(GroupCreateView.as_view()), name='group-create'),
    path('group-edit/<int:id>', login_required(GroupUpdateView.as_view()), name='group-edit'),
]

url_templates = [
    path('', login_required(TemplateListView.as_view()), name='templates'),
    path('create', login_required(TemplateCreateView.as_view()), name='template-create'),
    path('edit/<int:id>', login_required(TemplateUpdateView.as_view()), name='template-edit'),
]

url_mailing = [
    path('', login_required(MailingSendView.as_view()), name='mailing'),
    path('maling-send/group', login_required(MailingSendView.ajax_selected_groups), name='groups-ajax'),
]

url_logs = [
    path('', login_required(MailingListView.as_view()), name='logs'),
    path('details/<int:id>', login_required(MailingDetailView.as_view()), name='details'),

]

urlpatterns = [
	path('', login_required(TemplateView.as_view(template_name='mailing_index.html')), name='index'),
	path('start/', include(url_mailing)),
    path('logs/', include(url_logs)),
    path('templates/', include(url_templates)),
	path('groups/', include(url_groups)),
	path('users/', include(url_users)),
]

scc/scc/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

app_name='scc'


urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')), # multiple url's for accounts
	path('', TemplateView.as_view(template_name='home.html'), name='home'), # home page
    path('admin/', admin.site.urls), # admin page
	path('mailing/', include('mailing.urls')), # mailing page
	# you can add more for other app's
]

scc/mailing/models.py
from django.db import models
from mdeditor.fields import MDTextField
# Create your models here.

# post of user in school, literally just job
class Post(models.Model):
    post_name = models.CharField(max_length=64, unique=True)
    def __str__(self):
        return self.post_name

# school of user
class School(models.Model):
    school_name = models.CharField(max_length=255, unique=True)
    def __str__(self):
        return self.school_name
    class Meta:
        verbose_name = 'School'
        verbose_name_plural = 'Schools'

# department of user
class Department(models.Model):
    department_name = models.CharField(max_length=255)
    def __str__(self):
        return self.department_name
    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'

# user model
class SCC_User(models.Model):
    service_memo_number = models.CharField(max_length=255)
    service_registration_date = models.DateField(blank=False)
    last_name = models.CharField(max_length=64, blank=False)
    first_name = models.CharField(max_length=64, blank=False)
    surname = models.CharField(max_length=64, blank=True, null=True)
    login = models.CharField(max_length=64, null=False, blank=False, unique=True)
    number = models.CharField(max_length=64, blank=True, null=True)
    spin_code = models.CharField(max_length=16, blank=True, null=True)
    researcher_id = models.CharField(max_length=16, blank=True, null=True)
    science_project = models.CharField(max_length=255, blank=True, null=True)
    science_mentor = models.CharField(max_length=255, blank=True, null=True)
    access_ip = models.CharField(max_length=255, blank=True, null=True)
    commentary = models.TextField(default='', blank=True)

    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    school = models.ForeignKey(School, on_delete=models.SET_NULL, null=True)
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.id) + ' : ' + str(self.last_name) + ' ' + str(self.first_name) + ' : ' + str(self.login)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

class Email_to_user(models.Model):
    user = models.ForeignKey(SCC_User, on_delete=models.CASCADE)
    email =	models.EmailField(max_length=64, blank=False, unique=True)
    def __str__(self):
        return str(self.email) + ' : ' + str(self.user)
    class Meta:
        verbose_name = 'User-email relation'
        verbose_name_plural = 'User-email relations'

class Group(models.Model):
    group_name = models.CharField(max_length=255, unique=True)
    def __str__(self):
        return self.group_name
    class Meta:
        verbose_name = 'Group'
        verbose_name_plural = 'Groups'

class Group_to_user(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(SCC_User, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.group) + ' - ' + str(self.user)
    class Meta:
        verbose_name = 'Group-user relation'
        verbose_name_plural = 'Group-user relations'

class Template(models.Model):
    template_name = models.CharField(max_length=255, blank=False, unique=True)
    template_date = models.DateTimeField(auto_now_add=True, blank=True)

    template_text = MDTextField()

    def __str__(self):
        return str(self.template_name) + ' : ' + str(self.template_date)
    class Meta:
        verbose_name = 'Template'
        verbose_name_plural = 'Templates'

class Mailing(models.Model):
    mailing_name = models.CharField(max_length=255, blank=False)
    mailing_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.mailing_name) + " : " + str(self.mailing_date)
    class Meta:
        verbose_name = 'Mailing_names'
        verbose_name_plural = 'Mailings_names'

class Mailing_log(models.Model):
    mailing =       models.ForeignKey(Mailing, on_delete=models.CASCADE, null=True)
    group = 		models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    user = 			models.ForeignKey(SCC_User, on_delete=models.CASCADE, null=True)
    template = 		models.ForeignKey(Template, on_delete=models.CASCADE)
    result =        models.IntegerField()
    def __str__(self):
        return str(self.mailing)
    class Meta:
        verbose_name = 'Mailing'
        verbose_name_plural = 'Mailings'

scc/mailing/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView, CreateView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.forms.models import model_to_dict
import json
import mammoth
import io
import markdown
import openpyxl
from .xlsx_import import *
from .classes import *
from .models import *
from .forms import *


class UserListView(ListView): # add search
    model = SCC_User
    context_object_name = 'user_list'
    template_name = 'mailing_users.html'
    paginate_by = 50

    def get(self, request):
        users = self.model.objects.all()
        data = Actions.get_user_info(users)

        # paginate data (recomennded to be ordered)
        # paginator = Paginator(data, self.paginate_by)
        # page = request.GET.get('page')

        # try:
        #     paginated = paginator.get_page(page)
        # except PageNotAnInteger:
        #     paginated = paginator.get_page(1)
        # except EmptyPage:
        #     paginated = paginator.get_page(paginator.num_pages)

        return render(request, self.template_name, {
            'DataPaginated': data,
            # 'paginate_by': self.paginate_by
        })

    def post(self, request):
        if request.POST.get('Edit'):
            users_id = request.POST.getlist('checked-users')
            if users_id:
                return redirect('mailing:users-edit', ids=users_id)
        if request.POST.get('Create'):
            return redirect('mailing:create')
        if request.POST.get('Remove'):
            users_id = request.POST.getlist('checked-users')
            if (users_id):
                users_id = [int(x) for x in users_id]
                self.model.objects.filter(id__in=users_id).delete()
        if request.POST.get('Back'):
            return redirect('mailing:index')
        if request.POST.get('Import') and request.FILES:
            file = request.FILES['File']
            _, extension = os.path.splitext(file.name)
            bytes = io.BytesIO(file.read())
            if extension == '.xlsx':
                wrkbook = openpyxl.load_workbook(bytes)
                ws = wrkbook.active
                Importer.load_from_xlsx(ws)


        return redirect('mailing:users')


class UserCreateView(CreateView):
    model = SCC_User
    fields = '__all__'
    template_name = 'mailing_users_create.html'

    def get(self, request):
        user_form = {}
        user_form['form'] = UserUpdateForm()

        groups = Group.objects.all()

        posts = Post.objects.all()
        schools = School.objects.all()
        departments = Department.objects.all()

        return render(request, self.template_name, {
            'user_form': user_form,
            'groups': groups,
            'posts': posts,
            'schools': schools,
            'departments': departments,
        })

    def post(self, request):
        if request.POST.get('Confirm') or request.POST.get('Add-another'):
            form = UserUpdateForm(request.POST)
            if form.is_valid():
                form.save()
                new_user = self.model.objects.latest('id')

                # groups
                checked_groups = request.POST.getlist('checked-groups-new')
                checked_groups = list(map(int, checked_groups))

                for c in checked_groups:
                    group = Group.objects.get(pk=c)
                    Group_to_user(group=group, user=new_user).save()

                #foreign keys
                post = request.POST.get('post')
                department = request.POST.get('department')
                school = request.POST.get('school')

                try:
                    new_user.post = Post.objects.get_or_create(post_name=post)[0]
                    new_user.school = School.objects.get_or_create(school_name=school)[0]
                    new_user.department = Department.objects.get_or_create(department_name=department)[0]
                    
                    new_user.save()
                except Exception as e: # handle error in future 
                    print(e)

                # emails
                new_emails = request.POST.getlist('new-email')
                for email in new_emails:
                    if email:
                        Email_to_user(user_id=new_user.id, email=email).save()
            if request.POST.get('Add-another'):
                return redirect('mailing:create')

        return redirect('mailing:users')


class UserUpdateView(UpdateView):
    model = SCC_User
    template_name = 'mailing_users_edit.html'

    def get(self, request, ids):
        ids = Actions.string_list_to_list(ids)
        users = Actions.get_user_info(self.model.objects.filter(id__in=ids))
        groups = Group.objects.all()

        posts = Post.objects.all()
        schools = School.objects.all()
        departments = Department.objects.all()

        data = []
        for u in users:
            user_data = dict()
            user_data['id'] = u['user'].id
            user_data['form'] = UserUpdateForm(
                instance=u['user'], prefix=user_data['id'])
            
            group_data = []
            for g in groups:
                group_info = {
                    'group': g,
                    'is_in': Group_to_user.objects.filter(group__exact=g.id, user__exact=u['user'].id).exists()
                }
                group_data.append(group_info)
            user_data['group'] = group_data

            if posts.filter(post_name__exact=u['user'].post).exists():
                user_data['post'] = {
                    'id': posts.filter(post_name__exact=u['user'].post).values('id')[0]['id'],
                    'name': u['user'].post
                }
            if schools.filter(school_name__exact=u['user'].school).exists():
                user_data['school'] = {
                    'id': schools.filter(school_name__exact=u['user'].school).values('id')[0]['id'],
                    'name': u['user'].school
                }
            if departments.filter(department_name__exact=u['user'].department).exists():
                user_data['department'] = {
                    'id': departments.filter(department_name__exact=u['user'].department).values('id')[0]['id'],
                    'name': u['user'].department
                }
            user_data['emails'] = u['emails']
            data.append(user_data)

        return render(request, self.template_name, {
            'user_forms': data,
            'posts': posts,
            'schools': schools,
            'departments': departments,

        })

    def post(self, request, ids):
        ids = Actions.string_list_to_list(ids)

        for i in ids:
            form = UserUpdateForm(
                request.POST, instance=get_object_or_404(self.model, pk=i), prefix=i)
            if form.is_valid():
                form.save()

                #groups
                checked_groups = request.POST.getlist('checked-groups-' + str(i))
                checked_groups = list(map(int, checked_groups))

                excluded_groups = Group_to_user.objects.filter(user__exact=i).exclude(group__in=checked_groups)
                excluded_groups.delete()

                for c in checked_groups:
                    if not Group_to_user.objects.filter(group__exact=c, user__exact=i).exists():
                        group = Group.objects.get(pk=c)
                        user = SCC_User.objects.get(pk=i)
                        Group_to_user(group=group, user=user).save()

                # foreign keys
                post = request.POST.get('post' + str(i))
                department = request.POST.get('department' + str(i))
                school = request.POST.get('school' + str(i))

                try:
                    user = get_object_or_404(self.model, pk=i)
                    # get only instance
                    user.post = Post.objects.get_or_create(post_name=post)[0]
                    user.school = School.objects.get_or_create(school_name=school)[0]
                    user.department = Department.objects.get_or_create(department_name=department)[0]
                    
                    user.save()
                except Exception as e: # handle error in future 
                    print(e)
                    

                # emails
                emails_before = Email_to_user.objects.filter(
                    user_id__exact=i).values_list('id', flat=True)
                emails_before = list(emails_before)

                old_emails = request.POST.getlist('email' + str(i))
                old_emails_ids = request.POST.getlist('email-id' + str(i))
                old_emails_ids = [int(x) for x in old_emails_ids]
                deleted_emails = list(set(emails_before)-set(old_emails_ids))
                Email_to_user.objects.filter(id__in=deleted_emails).delete()

                email_dict = dict(zip(old_emails_ids, old_emails))
                for id in old_emails_ids:
                    Email_to_user.objects.filter(
                        id__exact=id).update(email=email_dict[id])

                new_emails = request.POST.getlist('new-email' + str(i))
                for email in new_emails:
                    if email and not Email_to_user.objects.filter(email__exact=email).exists():
                        Email_to_user(user_id=i, email=email).save()
        return redirect('mailing:users')
    
    def ajax_post(request):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            data = json.load(request)
            post = data['post']

            if request.method == "POST":
                if data['op'] == 'create':
                    is_exist = False

scc/mailing/templates/mailing_base.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
    <meta charset="utf-8">
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    {% block stylesheet %}
    {% endblock %}
    {% block header_scripts %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'mailing:index' %}">Mailing</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:mailing' %}">Рассылка</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:templates' %}">Шаблоны</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:groups' %}">Группы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:users' %}">Пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:logs' %}">Логи</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% block footer_scripts %}
    {% endblock %}
</body>

</html>

scc/mailing/templates/mailing_groups_create.html
{% extends 'mailing_base.html' %}

{% block title %}Groups{% endblock %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block header_scripts %}
<script src="{% static 'header-actions.js' %}"></script>
<script src="{% static 'modal.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="sticky-top">
            <a href="{% url 'mailing:groups' %}">
                <button type="button" class="btn btn-outline-secondary">Назад</button>
            </a>
            <button type="submit" class="btn btn-outline-primary" value="Edit" name="Edit">Редактировать пользователей</button>
            <button type="submit" class="btn btn-primary" value="Confirm" name="Confirm">Подтвердить</button>
        </div>
        <hr>
        <div class="containter">
            <div class="row group-edit-form">
                <div class="col font-weight-bold">
                    {{ group.as_table }}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

scc/mailing/templates/mailing_users_create.html
{% extends 'mailing_base.html' %}
{% load static %}

{% block title %}User Edit{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block header_scripts %}
<script src="{% static 'header-actions.js' %}"
        data-url-post = "{% url 'mailing:post-ajax' %}"
        data-url-school = "{% url 'mailing:school-ajax' %}"
        data-url-department = "{% url 'mailing:department-ajax' %}"
></script>
{% endblock %}


{% block content %}
<div class="container">
    <form method="post">
        <div class="containter sticky-top">
            <a href="{% url 'mailing:users' %}">
                <button type="button" class="btn btn-outline-secondary">Назад</button>
            </a>
            <input type="submit" class="btn btn-outline-primary" name="Add-another" value="Подтвердить и создать еще">
            <input type="submit" class="btn btn-primary" name="Confirm" value="Подтвердить">
        </div>
        {% csrf_token %}
        <div class="container-fluid pb-5" name="user-form">
            <hr>
            <p class="font-weight-bold">Создание пользователя</p>
            <hr>
            <div class="container d-flex mx-auto my-auto">
                <div class="col-sm-7">
                    <table class="table-responsive font-weight-normal">
                        {{ user_form.form.as_table }}
                    </table>
                        <table>
                            <tr>
                                <th>
                                    <label>Должность</label>
                                </th>
                                <td>
                                    <div class="select-editable user-edit-form-row">
                                        <select id="select-post" 
                                        onchange="this.nextElementSibling.value=this.value; 
                                        this.nextElementSibling.setAttribute('data-id', $(this).find('option:selected').attr('data-id'));
                                        this.nextElementSibling.setAttribute('value', $(this).find('option:selected').attr('value'))">
                                            <option data-id="-1" name="user-posts" value="" hidden></option>
                                            {% for p in posts %}
                                            <option data-id="{{ p.id }}" name="user-posts" value="{{ p.post_name }}" >{{ p.post_name }}</option>
                                            {% endfor %}
                                        </select>
                                        <input type="text"
                                            id="input-post"
                                            data-id=""
                                            name="post"
                                            oninput="this.previousElementSibling.options[0].setAttribute('data-id', this.getAttribute('data-id')); this.previousElementSibling.options[0].value=this.value; this.previousElementSibling.options[0].innerHTML=this.value"
                                            onchange="this.previousElementSibling.selectedIndex=0" value="">
                                    </div>
                                </td>
                                <td>
                                    <input id="foreign-post-create" data-operation="create" class="btn btn-sm btn-outline-secondary" type="button" value="Создать" name="post-create">
                                    <input id="foreign-post-update" data-operation="update" class="btn btn-sm btn-outline-secondary" type="button" value="Обновить" name="post-update">
                                    <input id="foreign-post-delete" data-operation="delete" class="btn btn-sm btn-outline-secondary" type="button" value="Удалить" name="post-delete">
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    <label>Институт</label>
                                </th>
                                <td>
                                    <div class="select-editable user-edit-form-row">
                                        <select id="select-school" 
                                        onchange="this.nextElementSibling.value=this.value; 
                                        this.nextElementSibling.setAttribute('data-id', $(this).find('option:selected').attr('data-id'));
                                        this.nextElementSibling.setAttribute('value', $(this).find('option:selected').attr('value'))">
                                            <option data-id="-1" name="user-posts" value="" hidden></option>
                                            {% for s in schools %}
                                            <option data-id="{{ s.id }}" name="user-school" value="{{ s.school_name }}" readonly>{{ s.school_name }}</option>
                                            {% endfor %}
                                        </select>
                                        <input type="text"
                                            id="input-school"
                                            data-id=""
                                            name="school"
                                            oninput="this.previousElementSibling.options[0].setAttribute('data-id', this.getAttribute('data-id')); this.previousElementSibling.options[0].value=this.value; this.previousElementSibling.options[0].innerHTML=this.value"
                                            onchange="this.previousElementSibling.selectedIndex=0" value="">
                                    </div>
                                </td>
                                <td>
                                    <input id="foreign-school-create" data-operation="create" class="btn btn-sm btn-outline-secondary" type="button" value="Создать" name="school-create">
                                    <input id="foreign-school-update" data-operation="update" class="btn btn-sm btn-outline-secondary" type="button" value="Обновить" name="school-update">
                                    <input id="foreign-school-delete" data-operation="delete" class="btn btn-sm btn-outline-secondary" type="button" value="Удалить" name="school-delete">
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    <lable>Кафедра</lable>
                                </th>
                                <td>
                                    <div class="select-editable user-edit-form-row">
                                        <select id="select-department" 
                                        onchange="this.nextElementSibling.value=this.value; 
                                        this.nextElementSibling.setAttribute('data-id', $(this).find('option:selected').attr('data-id'));
                                        this.nextElementSibling.setAttribute('value', $(this).find('option:selected').attr('value'))">
                                            <option data-id="-1" name="user-posts" value="" hidden></option>
                                            {% for d in departments %}
                                            <option data-id="{{ d.id }}" name="user-department" value="{{ d.department_name }}" readonly>{{ d.department_name }}</option>
                                            {% endfor %}
                                        </select>
                                        <input type="text"
                                            id="input-department"
                                            name="department"
                                            data-id=""
                                            oninput="this.previousElementSibling.options[0].setAttribute('data-id', this.getAttribute('data-id')); this.previousElementSibling.options[0].value=this.value; this.previousElementSibling.options[0].innerHTML=this.value"
                                            onchange="this.previousElementSibling.selectedIndex=0" value="">
                                    </div>
                                </td>
                                <td>
                                    <input id="foreign-department-create" data-operation="create" class="btn btn-sm btn-outline-secondary" type="button" value="Создать" name="school-create">
                                    <input id="foreign-department-update" data-operation="update" class="btn btn-sm btn-outline-secondary" type="button" value="Обновить" name="school-update">
                                    <input id="foreign-department-delete" data-operation="delete" class="btn btn-sm btn-outline-secondary" type="button" value="Удалить" name="school-delete">
                                </td>
                            </tr>
                        </table>
                    </div>
                <div class="col-sm-3">
                    <table class="d-block">
                        <thead>
                            <th scope="col">Почта</th>
                        </thead>
                        <tbody id="tbl-email">
                           <tr>
                                <td>
                                    <input type="email" name="new-email">
                                </td>
                                <td>
                                    <input type="button" class="btn btn-sm btn-outline-danger" value="Удалить" onclick="DeleteRow(this)">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <button type="button" class="w-100 ml-2 btn btn-outline-primary" id="add-row-email" name="add-email">Добавить почту</button>
                </div>
                <div class="col">
                    <table class="d-block ml-5">
                        <thead>
                            <th scope="col">Группы</th>
                            <th scope="col">
                                <input type="checkbox" name="select-all" id="select-all-new" value="new">
                            </th>
                        </thead>
                        <tbody>
                        {% for g in groups %}
                            <tr scope="row">
                                <td scope="row">
                                    {{ g.group_name }}
                                </td>
                                <td>
                                    <input type="checkbox" value="{{g.id}}" name="checked-groups-new">
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <hr>
    </form>
</div>
{% endblock %}