scc/mailing/urls.py
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView
from django.contrib.auth.decorators import login_required
from .views import *

app_name='mailing'

url_users = [
	path('', login_required(UserListView.as_view()), name='users'),
    path('create', login_required(UserCreateView.as_view()), name='create'),
	path('edit/<ids>', login_required(UserUpdateView.as_view()), name='users-edit'),
    path('edit-send/post', login_required(UserUpdateView.ajax_post), name='post-ajax'),
    path('edit-send/school', login_required(UserUpdateView.ajax_school), name='school-ajax'),
    path('edit-send/department', login_required(UserUpdateView.ajax_department), name='department-ajax'),
]

url_groups = [
    path('', login_required(GroupListView.as_view()), name='groups'),
    path('group-create', login_required(GroupCreateView.as_view()), name='group-create'),
    path('group-edit/<int:id>', login_required(GroupUpdateView.as_view()), name='group-edit'),
]

url_templates = [
    path('', login_required(TemplateListView.as_view()), name='templates'),
    path('create', login_required(TemplateCreateView.as_view()), name='template-create'),
    path('edit/<int:id>', login_required(TemplateUpdateView.as_view()), name='template-edit'),
]

url_mailing = [
    path('', login_required(MailingSendView.as_view()), name='mailing'),
    path('maling-send/group', login_required(MailingSendView.ajax_selected_groups), name='groups-ajax'),
]

url_logs = [
    path('', login_required(MailingListView.as_view()), name='logs'),
    path('details/<int:id>', login_required(MailingDetailView.as_view()), name='details'),

]

urlpatterns = [
	path('', login_required(TemplateView.as_view(template_name='mailing_index.html')), name='index'),
	path('start/', include(url_mailing)),
    path('logs/', include(url_logs)),
    path('templates/', include(url_templates)),
	path('groups/', include(url_groups)),
	path('users/', include(url_users)),
]

scc/scc/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

app_name='scc'


urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')), # multiple url's for accounts
	path('', TemplateView.as_view(template_name='home.html'), name='home'), # home page
    path('admin/', admin.site.urls), # admin page
	path('mailing/', include('mailing.urls')), # mailing page
	# you can add more for other app's
]

scc/scc/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Home{% endblock %}</title>
	</head>
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>

scc/scc/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	<h2>Pages:</h2>
	<p>
		<a href="{% url 'admin:index' %}">Admin page</a>
	</p>
	<p>
		<a href="{% url 'mailing:index' %}">Mailing page</a>
	</p>
	<p>
		<a href="{% url 'logout' %}">Logout</a>
	</p>
{% else %}
	<p>You are not logged in!</p>
	<a href="{% url 'login' %}">Log In</a>
{% endif %}

{% endblock %}